---
about_content: |
    Hi am a data scientist and entrepreneur looking for new challenges in the field of data science and machine learning.

    I am most skilled in: <mark>machine learning</mark> and <mark>scientific research</mark>.
about_profile_image: images/profile.jpg
additional_links:
  -
    icon: "fas fa-globe"
    title: itsgoingto.be
    url: "https://www.itsgoingto.be"
content:
  -
    content:
      -
        caption: "January 2018 - September 2018"
        description: "I’ve conducted electrophysiology experiments and analyzed data (Matlab). "
        layout: left
        quote: "Differences in Neural Mechanisms of Mismatch Negativity. Responses Across Conscious and Non-Conscious Brain States"
        sub_title: "University of Amsterdam"
        title: "Research Intern @ Swammerdam Institute for Life Sciences"
    layout: list
    title: "Work Experience"
darkmode: false
email: p.oosterholt@gmail.com
favicon: images/favicon.ico
footer_show_references: true
github_username: PhilipOosterholt
linkedin_username: jameswgrant
name: "Philip Oosterholt"
plugins:
  - jekyll-seo-tag
remote_theme: sproogen/resume-theme
repository: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
title: "Data scientist"
version: 2
website: philipoosterholt@github.io
