---
about_content: |
    I am a data scientist and entrepreneur looking for new data science
    challenges. <br><br><b>Why I love being a data scientist</b>. Before
    discovering data science, I was on track for a career as a researcher in
    neuroscience. I love deciphering mysteries—especially when no one has solved
    the mysteries before. However, science can be slow and lonesome.
    I realised that most researchers work years on end
    to answer one question. Along the way, I discovered that applying my
    knowledge and skills is the most exciting part of the journey. On an hour to
    hour basis you edge closer to solving the puzzle. Just as in science, there
    is little repetition in data science. While there are certainly best
    practices, each problem requires a tailor made approach. Data can help me
    understand the world—and with a fresh look and approach, I can even help
    experts to get a better grasp on their own field. <br><br>Apart from my love
    for data, I have an entrepreneurial mindset. In 2014, I co-founded
    BrainFitness, a platform for neurotech for consumers. The company
    was successfully sold in 2017. <br><br>In my spare time, I like to sport
    (&#127947;, &#x1F9D7;, &#127934; & &#x1f6b4;), game &#127918; (Civilization
    VI), watch movies &#127909; and follow SpaceX &#128640;
about_profile_image: images/me.jpg

content:
  - layout: text
    title: <b>My Skills</b>
    content: |
      <b>Programming languages (advanced)</b>: <mark>Python</mark> and
      <mark>MATLAB</mark>. I can work with scientific libraries (<mark>SciPy</mark>,
      <mark>NumPy</mark>), data science libraries (<mark>scikit-learn</mark> and
      <mark>pandas</mark>), deep learning frameworks (<mark>PyTorch</mark>, and
      to lesser extent <mark>Keras</mark> and <mark>TensorFlow</mark>), and data
      visualization libraries (<mark>Matplotlib</mark> and <mark>JavaScript D3
      </mark>). <br><br><b>Programming languages (basic)</b>: <mark>C</mark> and
      <mark>C#</mark>. <br><br><b>Query/markup languages</b>: <mark>SQL</mark>
      (intermediate), <mark>HTML</mark> (intermediate), <mark>CSS</mark>
      (intermediate) and <mark>Markdown</mark>(intermediate). <br><br><b>
      Applications</b>: <mark>Unity</mark> (basic), <mark>Wordpress</mark>
      (intermediate), <mark>Photoshop</mark> (basic). <br><br><b>Soft skills:
      </b> I am a critical thinker with a conscientious work attitude. My
      entrepreneurial past taught me how to work in a team and communicate
      with stakeholders. I learned how to identify and take advantage of
      business opportunities. I am skilled in communicating findings in speech
      and writing as well as presenting the findings visually.

  - layout: list
    title: <b>Work Experience</b>
    content:
      - caption: "September 2019 - December 2020"
        description: "<b>Depth in Convolutional Neural Networks Accomplish
        Scene Segmentation through the Selection of High-level Object Features</b>.
        Before starting the internship, I taught myself how to build and train
        <mark>deep convolutional neural networks</mark> (DCNNs). State-of-the-art
        DCNNs show impressive object recognition capabilities that rival our
        visual system. The internal state of these networks can predict neural
        data to an unprecedented degree. During the internship, I single handedly
        set up a new research line in <mark>Unity</mark> for researching the
        human visual system with DCNNs as computational models. The Unity
        environment enabled us to generate large datasets while retaining
        the experimental control necessary for scientific research. I
        subsequently built, trained and explored the DCNNs in <mark>PyTorch</mark>.
        <br><br>We are currently working to publish our results in a journal.
        At the end of my internship an AI master student continued the line of
        research. Download the PDF [here](./pdf/internship.pdf)."
        layout: left
        sub_title: "<br>University of Amsterdam <br> ◉ Grade 9.5/10 <br>"
        title: "Deep Learning Research Intern @ ScholteLab"
      - caption: "January 2018 - September 2018"
        description: "<b>The Differences in Neural Mechanisms of Mismatch
        Negativity: Responses Across Conscious and Non-Conscious Brain States</b>.
        During the internship, I conducted electrophysiology experiments in mice
        and analyzed the data in <mark>MATLAB</mark>.
        <br><br>My supervisor is currently prepping the papers for publication
        and I will be included as aa co-author for some of the publications."
        layout: left
        sub_title: "<br>University of Amsterdam"
        title: "Research Intern @ Swammerdam Institute for Life Sciences"
      - caption: "2014 - 2017"
        description: "BrainFitness is a platform for consumer neurotechnology in
        the Netherlands. Our mission is to accelerate the adoption of
        neurotechnology in the Netherlands. We bring the most innovative
        neurotechnology to the Dutch market and make it available for consumers,
        companies and healthcare Professionals. The company was sold in 2017."
        layout: left
        title: BrainFitness
        sub_title: Co-Founder and CEO

  - layout: list
    title: <b>Education</b>
    content:
      - caption: "2017 - 2020 (120 ECTS)"
        description: "The Research Master's programme in Brain and Cognitive
        Sciences at the University of Amsterdam offers a broad selection of
        tracks that investigate all aspects of the field, from the molecule to
        the mind. The programme is unique in its interdisciplinary perspective
        that incorporates the fields of neuroscience, neurology, psychology,
        behavioural economics, linguistics, logic, computation and philosophy.
        The brain is an immensely powerful and intricate processing device
        dedicated to the selection, perception, transformation and storage of
        the indispensable information we use to interact with our ever-changing,
        dynamic environment. <br><br>I followed the Cognitive Neuroscience Track."
        layout: left
        sub_title: "<br>University of Amsterdam <br> ◉ GPA 8.6/10"
        title: "Research Master Brain and Cognitive Sciences"
      - caption: "September 2018 - February 2019 (30 ECTS)"
        description: "The minor programming teaches beginning and intermediate
        coders how to write clean and fast code as well as how to use coding
        to solve complex problems. In the minor I worked with <mark>Python
        </mark>, <mark>C</mark> and <mark>JavaScript D3</mark>. Moreover, I
        learned how to code in teams and use version control in GitHub. I
        followed the <mark>data processing</mark> and <mark>data visualization
        </mark> track."
        layout: left
        sub_title: "University of Amsterdam <br> ◉ GPA 8.5/10"
        title: "Minor Programming"
      - caption: "September 2011 - July 2014 (210 ECTS)"
        description: "Human behaviour often appears to be predictable. But on
        closer inspection, it turns out to be less obvious than you think.
        Can behaviour ever be understood? And can it influenced? The programme
        not only looks at the general characteristicss of human behaviour, but
        focuses particularly on differences between behaviour.<br><br> I
        followed the track Brain and Cognition. The goal of the track is to
        obtain a better understanding of the nature of human cognition and its
        neural basis. The track emphasizes theory development, attempts to base
        explanations for cognitive phenomena on neurobiological principles, and
        has a focus on using cognitive research to understand clinical findings.
        <br><br> Next to the regular bachelor, I followed the Honours programme."
        layout: left
        sub_title: "University of Amsterdam<br>◉ GPA 8.5/10"
        title: "BSc Psychology"

  - layout: list
    title: <b>Thesis</b>
    content:
      - caption: "2020"
        title: Brain and Cognitive Sciences
        sub_title: "University of Amsterdam <br> ◉ Grade 9/10"
        description: "<b>Supervised and Self-Supervised Learning in Deep
        Convolutional Neural Networks as Computational Models for Object
        Recognition.</b> Read the PDF [here](./pdf/thesis.pdf)."
        layout: left

  - layout: list
    title: <b>Additional courses</b>
    content:
      - caption: "2019"
        description: "Deep learning - Coursera (certificate: YA7MT8RX6MMR)<br>
        Data scientist with Python - DataCamp<br> Deep learning Fast.AI (2019
        version, audited)<br>Introduction to Machine Learning for Coders -
        Fast.AI (audited)<br>Essential Math for Machine Learning: Python Edition
        - Microsoft (audited)<br> Deep Learning with Python and PyTorch - IBM
        (audited)"
        layout: left

  - layout: list
    title: <b>Awards</b>
    content:
      - caption: "2012"
        description: "Thesis of the Year UvA Psychology: Christiaan Hamaker Trofee"
        layout: left

darkmode: false
email: p.oosterholt@gmail.com
favicon: images/favicon.ico
footer_show_references: true
github_username: PhilipOosterholt
linkedin_username: philip-oosterholt
name: "Philip Oosterholt"
plugins:
  - jekyll-seo-tag
remote_theme: sproogen/resume-theme
repository: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
title: "Data scientist"
version: 2
website: philipoosterholt@github.io
