---
about_content: |
    Hi am a data scientist and entrepreneur looking for new challenges in the field of data science and machine learning.

    I am most skilled in: <mark>machine learning</mark> and <mark>scientific research</mark>.
about_profile_image: images/profile.jpg
additional_links:
  -
    icon: "fas fa-globe"
    title: itsgoingto.be
    url: "https://www.itsgoingto.be"
content:
  -
    content:
      -
        caption: "September 2019 - December 2020"
        description: "I set up a new research line for the lab in the game engine Unity for researching vision with the help of deep convolutional neural networks. The Unity environment is capable of generating large datasets while retaining the experimental control necessary for scientific research. I subsequently trained and investigated convolutional neural networks in PyTorch"
        layout: left
        quote: "Depth in Convolutional Neural Networks Accomplish Scene Segmentation through the Selection of High-level Object Features"
        sub_title: "University of Amsterdam \nsplit ◉ Grade 9.5/10"
        title: "Deep Learning Research Intern @ Scholte lab"
    layout: list
    title: "Work Experience"
darkmode: false
email: p.oosterholt@gmail.com
favicon: images/favicon.ico
footer_show_references: true
github_username: PhilipOosterholt
linkedin_username: jameswgrant
name: "Philip Oosterholt"
plugins:
  - jekyll-seo-tag
remote_theme: sproogen/resume-theme
repository: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
title: "Data scientist"
version: 2
website: philipoosterholt@github.io
