---
about_content: |
    Hi am a data scientist and entrepreneur looking for new challenges in the field of data science and machine learning.

    I am most skilled in: <mark>machine learning</mark> and <mark>scientific research</mark>.
about_profile_image: images/profile.jpg
additional_links:
  -
    icon: "fas fa-globe"
    title: itsgoingto.be
    url: "https://www.itsgoingto.be"
content:
  -
    content:
      -
        caption: "September 2019 - December 2020"
        description: "I set up a new research line for the lab in the game engine Unity for researching vision with the help of deep convolutional neural networks. The Unity environment is capable of generating large datasets while retaining the experimental control necessary for scientific research. I subsequently trained and investigated convolutional neural networks in PyTorch"
        layout: left
        quote: "<b>Depth in Convolutional Neural Networks Accomplish Scene Segmentation through the Selection of High-level Object Features</b>"
        sub_title: "University of Amsterdam <br> ◉ Grade 9.5/10"
        title: "Deep Learning Research Intern @ Scholte lab"
    layout: list
    title: "Work Experience"
  -
    content:
      -
        caption: "January 2018 - September 2018"
        description: "I’ve conducted electrophysiology experiments and analyzed data (Matlab)."
        layout: left
        quote: "**The Differences in Neural Mechanisms of Mismatch Negativity. Responses Across Conscious and Non-Conscious Brain States**"
        sub_title: "University of Amsterdam"
        title: "Research Intern @ Swammerdam Institute for Life Sciences"
    layout: list
  -
    content:
      -
        caption: "2014 - 2017"
        description: "BrainFitness is a platform for consumer neurotechnology in the Netherlands. Our mission is to accelerate the adoption of neurotechnology in the Netherlands. We bring the most innovative neurotechnology to the Dutch market and make it available for consumers, companies and healthcare Professionals. The company was sold in 2017."
        layout: left
        title: "Co-Founder and CEO"
    layout: list
  -
    layout: list
    title: Education
    content:
      -
        caption: "2017 - 2020"
        description: "The Research Master's programme in Brain and Cognitive Sciences at the University of Amsterdam offers a broad selection of tracks that investigate all aspects of the field, from the molecule to the mind. The programme is unique in its interdisciplinary perspective that incorporates the fields of neuroscience, neurology, psychology, behavioural economics, linguistics, logic, computation and philosophy. The brain is an immensely powerful and intricate processing device dedicated to the selection, perception, transformation and storage of the indispensable information we use to interact with our ever-changing, dynamic environment."
        layout: left
        sub_title: "University of Amsterdam <br> Cognitive Neuroscience Track <br> ◉ GPA 8.6/10"
        title: "Research Master Brain and Cognitive Sciences"
  -
    layout: list
    content:
      -
        caption: "September 2018 - February 2019"
        description: ""
        layout: left
        sub_title: "University of Amsterdam <br> Cognitive Neuroscience Track <br> ◉ GPA 8.6/10"
        title: "Minor Programming"

darkmode: false
email: p.oosterholt@gmail.com
favicon: images/favicon.ico
footer_show_references: true
github_username: PhilipOosterholt
linkedin_username: jameswgrant
name: "Philip Oosterholt"
plugins:
  - jekyll-seo-tag
remote_theme: sproogen/resume-theme
repository: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
title: "Data scientist"
version: 2
website: philipoosterholt@github.io
